In [95]:
y_actual = [3, 4.5, 5, 6, 7]
y_pred = [2.5, 4.0, 6.0, 5.5, 8.0]

In [96]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [97]:
r2=r2_score(y_actual,y_pred)
mse=mean_squared_error(y_actual,y_pred)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_actual,y_pred)

In [98]:
print(r2)
print(mse)
print(rmse)
print(mae)

0.701086956521739
0.55
0.7416198487095663
0.7

In [99]:
import pandas as pd
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/caravan-insurance-challenge.csv')

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9822 entries, 0 to 9821
Data columns (total 87 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ORIGIN    9822 non-null   object
 1   MOSTYPE   9822 non-null   int64
 2   MAANTHUI  9822 non-null   int64
 3   MGEMOMV   9822 non-null   int64
 4   MGEMLEEF  9822 non-null   int64
 5   MOSHOOFD  9822 non-null   int64
 6   MGODRK    9822 non-null   int64
 7   MGODPR    9822 non-null   int64
 8   MGODOV    9822 non-null   int64
 9   MGODGE    9822 non-null   int64
 10  MRELGE    9822 non-null   int64
 11  MRELSA    9822 non-null   int64
 12  MRELOV    9822 non-null   int64
 13  MFALLEEN  9822 non-null   int64
 14  MFGEKIND  9822 non-null   int64
 15  MFWEKIND  9822 non-null   int64
 16  MOPLHOOG  9822 non-null   int64
 17  MOPLMIDD  9822 non-null   int64
 18  MOPLLAAG  9822 non-null   int64
 19  MBERHOOG  9822 non-null   int64
 20  MBERZELF  9822 non-null   int64
 21  MBERBOER  9822 non-null   int64
 22  MBERMIDD  9822 non-null   int64
 23  MBERARBG  9822 non-null   int64
 24  MBERARBO  9822 non-null   int64
 25  MSKA      9822 non-null   int64
 26  MSKB1     9822 non-null   int64
 27  MSKB2     9822 non-null   int64
 28  MSKC      9822 non-null   int64
 29  MSKD      9822 non-null   int64
 30  MHHUUR    9822 non-null   int64
 31  MHKOOP    9822 non-null   int64
 32  MAUT1     9822 non-null   int64
 33  MAUT2     9822 non-null   int64
 34  MAUT0     9822 non-null   int64
 35  MZFONDS   9822 non-null   int64
 36  MZPART    9822 non-null   int64
 37  MINKM30   9822 non-null   int64
 38  MINK3045  9822 non-null   int64
 39  MINK4575  9822 non-null   int64
 40  MINK7512  9822 non-null   int64
 41  MINK123M  9822 non-null   int64
 42  MINKGEM   9822 non-null   int64
 43  MKOOPKLA  9822 non-null   int64
 44  PWAPART   9822 non-null   int64
 45  PWABEDR   9822 non-null   int64
 46  PWALAND   9822 non-null   int64
 47  PPERSAUT  9822 non-null   int64
 48  PBESAUT   9822 non-null   int64
 49  PMOTSCO   9822 non-null   int64
 50  PVRAAUT   9822 non-null   int64
 51  PAANHANG  9822 non-null   int64
 52  PTRACTOR  9822 non-null   int64
 53  PWERKT    9822 non-null   int64
 54  PBROM     9822 non-null   int64
 55  PLEVEN    9822 non-null   int64
 56  PPERSONG  9822 non-null   int64
 57  PGEZONG   9822 non-null   int64
 58  PWAOREG   9822 non-null   int64
 59  PBRAND    9822 non-null   int64
 60  PZEILPL   9822 non-null   int64
 61  PPLEZIER  9822 non-null   int64
 62  PFIETS    9822 non-null   int64
 63  PINBOED   9822 non-null   int64
 64  PBYSTAND  9822 non-null   int64
 65  AWAPART   9822 non-null   int64
 66  AWABEDR   9822 non-null   int64
 67  AWALAND   9822 non-null   int64
 68  APERSAUT  9822 non-null   int64
 69  ABESAUT   9822 non-null   int64
 70  AMOTSCO   9822 non-null   int64
 71  AVRAAUT   9822 non-null   int64
 72  AAANHANG  9822 non-null   int64
 73  ATRACTOR  9822 non-null   int64
 74  AWERKT    9822 non-null   int64
 75  ABROM     9822 non-null   int64
 76  ALEVEN    9822 non-null   int64
 77  APERSONG  9822 non-null   int64
 78  AGEZONG   9822 non-null   int64
 79  AWAOREG   9822 non-null   int64
 80  ABRAND    9822 non-null   int64
 81  AZEILPL   9822 non-null   int64
 82  APLEZIER  9822 non-null   int64
 83  AFIETS    9822 non-null   int64
 84  AINBOED   9822 non-null   int64
 85  ABYSTAND  9822 non-null   int64
 86  CARAVAN   9822 non-null   int64
dtypes: int64(86), object(1)
memory usage: 6.5+ MB

In [101]:
df.isnull().sum()

ORIGIN      0
MOSTYPE     0
MAANTHUI    0
MGEMOMV     0
MGEMLEEF    0
           ..
APLEZIER    0
AFIETS      0
AINBOED     0
ABYSTAND    0
CARAVAN     0
Length: 87, dtype: int64

In [102]:
# Function + Missing qiymatlar
def tozala(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [103]:
tozala(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9822 entries, 0 to 9821
Data columns (total 87 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ORIGIN    9822 non-null   object
 1   MOSTYPE   9822 non-null   int64
 2   MAANTHUI  9822 non-null   int64
 3   MGEMOMV   9822 non-null   int64
 4   MGEMLEEF  9822 non-null   int64
 5   MOSHOOFD  9822 non-null   int64
 6   MGODRK    9822 non-null   int64
 7   MGODPR    9822 non-null   int64
 8   MGODOV    9822 non-null   int64
 9   MGODGE    9822 non-null   int64
 10  MRELGE    9822 non-null   int64
 11  MRELSA    9822 non-null   int64
 12  MRELOV    9822 non-null   int64
 13  MFALLEEN  9822 non-null   int64
 14  MFGEKIND  9822 non-null   int64
 15  MFWEKIND  9822 non-null   int64
 16  MOPLHOOG  9822 non-null   int64
 17  MOPLMIDD  9822 non-null   int64
 18  MOPLLAAG  9822 non-null   int64
 19  MBERHOOG  9822 non-null   int64
 20  MBERZELF  9822 non-null   int64
 21  MBERBOER  9822 non-null   int64
 22  MBERMIDD  9822 non-null   int64
 23  MBERARBG  9822 non-null   int64
 24  MBERARBO  9822 non-null   int64
 25  MSKA      9822 non-null   int64
 26  MSKB1     9822 non-null   int64
 27  MSKB2     9822 non-null   int64
 28  MSKC      9822 non-null   int64
 29  MSKD      9822 non-null   int64
 30  MHHUUR    9822 non-null   int64
 31  MHKOOP    9822 non-null   int64
 32  MAUT1     9822 non-null   int64
 33  MAUT2     9822 non-null   int64
 34  MAUT0     9822 non-null   int64
 35  MZFONDS   9822 non-null   int64
 36  MZPART    9822 non-null   int64
 37  MINKM30   9822 non-null   int64
 38  MINK3045  9822 non-null   int64
 39  MINK4575  9822 non-null   int64
 40  MINK7512  9822 non-null   int64
 41  MINK123M  9822 non-null   int64
 42  MINKGEM   9822 non-null   int64
 43  MKOOPKLA  9822 non-null   int64
 44  PWAPART   9822 non-null   int64
 45  PWABEDR   9822 non-null   int64
 46  PWALAND   9822 non-null   int64
 47  PPERSAUT  9822 non-null   int64
 48  PBESAUT   9822 non-null   int64
 49  PMOTSCO   9822 non-null   int64
 50  PVRAAUT   9822 non-null   int64
 51  PAANHANG  9822 non-null   int64
 52  PTRACTOR  9822 non-null   int64
 53  PWERKT    9822 non-null   int64
 54  PBROM     9822 non-null   int64
 55  PLEVEN    9822 non-null   int64
 56  PPERSONG  9822 non-null   int64
 57  PGEZONG   9822 non-null   int64
 58  PWAOREG   9822 non-null   int64
 59  PBRAND    9822 non-null   int64
 60  PZEILPL   9822 non-null   int64
 61  PPLEZIER  9822 non-null   int64
 62  PFIETS    9822 non-null   int64
 63  PINBOED   9822 non-null   int64
 64  PBYSTAND  9822 non-null   int64
 65  AWAPART   9822 non-null   int64
 66  AWABEDR   9822 non-null   int64
 67  AWALAND   9822 non-null   int64
 68  APERSAUT  9822 non-null   int64
 69  ABESAUT   9822 non-null   int64
 70  AMOTSCO   9822 non-null   int64
 71  AVRAAUT   9822 non-null   int64
 72  AAANHANG  9822 non-null   int64
 73  ATRACTOR  9822 non-null   int64
 74  AWERKT    9822 non-null   int64
 75  ABROM     9822 non-null   int64
 76  ALEVEN    9822 non-null   int64
 77  APERSONG  9822 non-null   int64
 78  AGEZONG   9822 non-null   int64
 79  AWAOREG   9822 non-null   int64
 80  ABRAND    9822 non-null   int64
 81  AZEILPL   9822 non-null   int64
 82  APLEZIER  9822 non-null   int64
 83  AFIETS    9822 non-null   int64
 84  AINBOED   9822 non-null   int64
 85  ABYSTAND  9822 non-null   int64
 86  CARAVAN   9822 non-null   int64
dtypes: int64(86), object(1)
memory usage: 6.5+ MB

In [104]:
tozala(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9822 entries, 0 to 9821
Data columns (total 87 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ORIGIN    9822 non-null   object
 1   MOSTYPE   9822 non-null   int64
 2   MAANTHUI  9822 non-null   int64
 3   MGEMOMV   9822 non-null   int64
 4   MGEMLEEF  9822 non-null   int64
 5   MOSHOOFD  9822 non-null   int64
 6   MGODRK    9822 non-null   int64
 7   MGODPR    9822 non-null   int64
 8   MGODOV    9822 non-null   int64
 9   MGODGE    9822 non-null   int64
 10  MRELGE    9822 non-null   int64
 11  MRELSA    9822 non-null   int64
 12  MRELOV    9822 non-null   int64
 13  MFALLEEN  9822 non-null   int64
 14  MFGEKIND  9822 non-null   int64
 15  MFWEKIND  9822 non-null   int64
 16  MOPLHOOG  9822 non-null   int64
 17  MOPLMIDD  9822 non-null   int64
 18  MOPLLAAG  9822 non-null   int64
 19  MBERHOOG  9822 non-null   int64
 20  MBERZELF  9822 non-null   int64
 21  MBERBOER  9822 non-null   int64
 22  MBERMIDD  9822 non-null   int64
 23  MBERARBG  9822 non-null   int64
 24  MBERARBO  9822 non-null   int64
 25  MSKA      9822 non-null   int64
 26  MSKB1     9822 non-null   int64
 27  MSKB2     9822 non-null   int64
 28  MSKC      9822 non-null   int64
 29  MSKD      9822 non-null   int64
 30  MHHUUR    9822 non-null   int64
 31  MHKOOP    9822 non-null   int64
 32  MAUT1     9822 non-null   int64
 33  MAUT2     9822 non-null   int64
 34  MAUT0     9822 non-null   int64
 35  MZFONDS   9822 non-null   int64
 36  MZPART    9822 non-null   int64
 37  MINKM30   9822 non-null   int64
 38  MINK3045  9822 non-null   int64
 39  MINK4575  9822 non-null   int64
 40  MINK7512  9822 non-null   int64
 41  MINK123M  9822 non-null   int64
 42  MINKGEM   9822 non-null   int64
 43  MKOOPKLA  9822 non-null   int64
 44  PWAPART   9822 non-null   int64
 45  PWABEDR   9822 non-null   int64
 46  PWALAND   9822 non-null   int64
 47  PPERSAUT  9822 non-null   int64
 48  PBESAUT   9822 non-null   int64
 49  PMOTSCO   9822 non-null   int64
 50  PVRAAUT   9822 non-null   int64
 51  PAANHANG  9822 non-null   int64
 52  PTRACTOR  9822 non-null   int64
 53  PWERKT    9822 non-null   int64
 54  PBROM     9822 non-null   int64
 55  PLEVEN    9822 non-null   int64
 56  PPERSONG  9822 non-null   int64
 57  PGEZONG   9822 non-null   int64
 58  PWAOREG   9822 non-null   int64
 59  PBRAND    9822 non-null   int64
 60  PZEILPL   9822 non-null   int64
 61  PPLEZIER  9822 non-null   int64
 62  PFIETS    9822 non-null   int64
 63  PINBOED   9822 non-null   int64
 64  PBYSTAND  9822 non-null   int64
 65  AWAPART   9822 non-null   int64
 66  AWABEDR   9822 non-null   int64
 67  AWALAND   9822 non-null   int64
 68  APERSAUT  9822 non-null   int64
 69  ABESAUT   9822 non-null   int64
 70  AMOTSCO   9822 non-null   int64
 71  AVRAAUT   9822 non-null   int64
 72  AAANHANG  9822 non-null   int64
 73  ATRACTOR  9822 non-null   int64
 74  AWERKT    9822 non-null   int64
 75  ABROM     9822 non-null   int64
 76  ALEVEN    9822 non-null   int64
 77  APERSONG  9822 non-null   int64
 78  AGEZONG   9822 non-null   int64
 79  AWAOREG   9822 non-null   int64
 80  ABRAND    9822 non-null   int64
 81  AZEILPL   9822 non-null   int64
 82  APLEZIER  9822 non-null   int64
 83  AFIETS    9822 non-null   int64
 84  AINBOED   9822 non-null   int64
 85  ABYSTAND  9822 non-null   int64
 86  CARAVAN   9822 non-null   int64
dtypes: int64(86), object(1)
memory usage: 6.5+ MB

In [105]:
df.isnull().sum()

ORIGIN      0
MOSTYPE     0
MAANTHUI    0
MGEMOMV     0
MGEMLEEF    0
           ..
APLEZIER    0
AFIETS      0
AINBOED     0
ABYSTAND    0
CARAVAN     0
Length: 87, dtype: int64

In [106]:
# import pandas as pd
# df=pd.read_csv('house_price.txt')

In [107]:
# df.isnull().sum()

In [108]:
from sklearn.preprocessing import LabelEncoder

In [109]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def encodla(df):
    encoder = LabelEncoder()

    for col in df.columns.to_list(): 
        if df[col].dtype == 'object':
            if df[col].nunique() <= 6:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df.drop(columns=[col], inplace=True)
                df[dummies.columns] = dummies
            else:
                df[col] = encoder.fit_transform(df[col].astype(str))
    
    return df

In [110]:
df = encodla(df)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9822 entries, 0 to 9821
Data columns (total 88 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MOSTYPE       9822 non-null   int64
 1   MAANTHUI      9822 non-null   int64
 2   MGEMOMV       9822 non-null   int64
 3   MGEMLEEF      9822 non-null   int64
 4   MOSHOOFD      9822 non-null   int64
 5   MGODRK        9822 non-null   int64
 6   MGODPR        9822 non-null   int64
 7   MGODOV        9822 non-null   int64
 8   MGODGE        9822 non-null   int64
 9   MRELGE        9822 non-null   int64
 10  MRELSA        9822 non-null   int64
 11  MRELOV        9822 non-null   int64
 12  MFALLEEN      9822 non-null   int64
 13  MFGEKIND      9822 non-null   int64
 14  MFWEKIND      9822 non-null   int64
 15  MOPLHOOG      9822 non-null   int64
 16  MOPLMIDD      9822 non-null   int64
 17  MOPLLAAG      9822 non-null   int64
 18  MBERHOOG      9822 non-null   int64
 19  MBERZELF      9822 non-null   int64
 20  MBERBOER      9822 non-null   int64
 21  MBERMIDD      9822 non-null   int64
 22  MBERARBG      9822 non-null   int64
 23  MBERARBO      9822 non-null   int64
 24  MSKA          9822 non-null   int64
 25  MSKB1         9822 non-null   int64
 26  MSKB2         9822 non-null   int64
 27  MSKC          9822 non-null   int64
 28  MSKD          9822 non-null   int64
 29  MHHUUR        9822 non-null   int64
 30  MHKOOP        9822 non-null   int64
 31  MAUT1         9822 non-null   int64
 32  MAUT2         9822 non-null   int64
 33  MAUT0         9822 non-null   int64
 34  MZFONDS       9822 non-null   int64
 35  MZPART        9822 non-null   int64
 36  MINKM30       9822 non-null   int64
 37  MINK3045      9822 non-null   int64
 38  MINK4575      9822 non-null   int64
 39  MINK7512      9822 non-null   int64
 40  MINK123M      9822 non-null   int64
 41  MINKGEM       9822 non-null   int64
 42  MKOOPKLA      9822 non-null   int64
 43  PWAPART       9822 non-null   int64
 44  PWABEDR       9822 non-null   int64
 45  PWALAND       9822 non-null   int64
 46  PPERSAUT      9822 non-null   int64
 47  PBESAUT       9822 non-null   int64
 48  PMOTSCO       9822 non-null   int64
 49  PVRAAUT       9822 non-null   int64
 50  PAANHANG      9822 non-null   int64
 51  PTRACTOR      9822 non-null   int64
 52  PWERKT        9822 non-null   int64
 53  PBROM         9822 non-null   int64
 54  PLEVEN        9822 non-null   int64
 55  PPERSONG      9822 non-null   int64
 56  PGEZONG       9822 non-null   int64
 57  PWAOREG       9822 non-null   int64
 58  PBRAND        9822 non-null   int64
 59  PZEILPL       9822 non-null   int64
 60  PPLEZIER      9822 non-null   int64
 61  PFIETS        9822 non-null   int64
 62  PINBOED       9822 non-null   int64
 63  PBYSTAND      9822 non-null   int64
 64  AWAPART       9822 non-null   int64
 65  AWABEDR       9822 non-null   int64
 66  AWALAND       9822 non-null   int64
 67  APERSAUT      9822 non-null   int64
 68  ABESAUT       9822 non-null   int64
 69  AMOTSCO       9822 non-null   int64
 70  AVRAAUT       9822 non-null   int64
 71  AAANHANG      9822 non-null   int64
 72  ATRACTOR      9822 non-null   int64
 73  AWERKT        9822 non-null   int64
 74  ABROM         9822 non-null   int64
 75  ALEVEN        9822 non-null   int64
 76  APERSONG      9822 non-null   int64
 77  AGEZONG       9822 non-null   int64
 78  AWAOREG       9822 non-null   int64
 79  ABRAND        9822 non-null   int64
 80  AZEILPL       9822 non-null   int64
 81  APLEZIER      9822 non-null   int64
 82  AFIETS        9822 non-null   int64
 83  AINBOED       9822 non-null   int64
 84  ABYSTAND      9822 non-null   int64
 85  CARAVAN       9822 non-null   int64
 86  ORIGIN_test   9822 non-null   int64
 87  ORIGIN_train  9822 non-null   int64
dtypes: int64(88)
memory usage: 6.6 MB

In [112]:
df.head()

,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,MRELGE,...,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,CARAVAN,ORIGIN_test,ORIGIN_train
0,33,1,3,2,8,0,5,1,3,7,...,0,1,0,0,0,0,0,0,0,1
1,37,1,2,2,8,1,4,1,4,6,...,0,1,0,0,0,0,0,0,0,1
2,37,1,2,2,8,0,4,2,4,3,...,0,1,0,0,0,0,0,0,0,1
3,9,1,3,3,3,2,3,2,4,5,...,0,1,0,0,0,0,0,0,0,1
4,40,1,4,2,10,1,4,1,4,7,...,0,1,0,0,0,0,0,0,0,1

In [113]:
from sklearn.preprocessing import MinMaxScaler

In [114]:
scaler=MinMaxScaler()

In [115]:
def scale_qil(df):
    for col in df.columns:
        if df[col].dtype!='object':
            df[col]=scaler.fit_transform(df[[col]])
    return df

In [116]:
df=scale_qil(df)

In [117]:
df.head()

,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,MRELGE,...,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,CARAVAN,ORIGIN_test,ORIGIN_train
0,0.800,0.0,0.4,0.2,0.777778,0.000000,0.555556,0.2,0.333333,0.777778,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.900,0.0,0.2,0.2,0.777778,0.111111,0.444444,0.2,0.444444,0.666667,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.900,0.0,0.2,0.2,0.777778,0.000000,0.444444,0.4,0.444444,0.333333,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.200,0.0,0.4,0.4,0.222222,0.222222,0.333333,0.4,0.444444,0.555556,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.975,0.0,0.6,0.2,1.000000,0.111111,0.444444,0.2,0.444444,0.777778,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [118]:
numerical_col = df.select_dtypes(include=['int32', 'float64']).columns.tolist()
if 'Income($)' in numerical_col:
    numerical_col.remove('Income($)')
print("Numeric columns to scale:", numerical_col)

Numeric columns to scale: ['MOSTYPE', 'MAANTHUI', 'MGEMOMV', 'MGEMLEEF', 'MOSHOOFD', 'MGODRK', 'MGODPR', 'MGODOV', 'MGODGE', 'MRELGE', 'MRELSA', 'MRELOV', 'MFALLEEN', 'MFGEKIND', 'MFWEKIND', 'MOPLHOOG', 'MOPLMIDD', 'MOPLLAAG', 'MBERHOOG', 'MBERZELF', 'MBERBOER', 'MBERMIDD', 'MBERARBG', 'MBERARBO', 'MSKA', 'MSKB1', 'MSKB2', 'MSKC', 'MSKD', 'MHHUUR', 'MHKOOP', 'MAUT1', 'MAUT2', 'MAUT0', 'MZFONDS', 'MZPART', 'MINKM30', 'MINK3045', 'MINK4575', 'MINK7512', 'MINK123M', 'MINKGEM', 'MKOOPKLA', 'PWAPART', 'PWABEDR', 'PWALAND', 'PPERSAUT', 'PBESAUT', 'PMOTSCO', 'PVRAAUT', 'PAANHANG', 'PTRACTOR', 'PWERKT', 'PBROM', 'PLEVEN', 'PPERSONG', 'PGEZONG', 'PWAOREG', 'PBRAND', 'PZEILPL', 'PPLEZIER', 'PFIETS', 'PINBOED', 'PBYSTAND', 'AWAPART', 'AWABEDR', 'AWALAND', 'APERSAUT', 'ABESAUT', 'AMOTSCO', 'AVRAAUT', 'AAANHANG', 'ATRACTOR', 'AWERKT', 'ABROM', 'ALEVEN', 'APERSONG', 'AGEZONG', 'AWAOREG', 'ABRAND', 'AZEILPL', 'APLEZIER', 'AFIETS', 'AINBOED', 'ABYSTAND', 'CARAVAN', 'ORIGIN_test', 'ORIGIN_train']

In [119]:
numerical_col

['MOSTYPE',
 'MAANTHUI',
 'MGEMOMV',
 'MGEMLEEF',
 'MOSHOOFD',
 'MGODRK',
 'MGODPR',
 'MGODOV',
 'MGODGE',
 'MRELGE',
 'MRELSA',
 'MRELOV',
 'MFALLEEN',
 'MFGEKIND',
 'MFWEKIND',
 'MOPLHOOG',
 'MOPLMIDD',
 'MOPLLAAG',
 'MBERHOOG',
 'MBERZELF',
 'MBERBOER',
 'MBERMIDD',
 'MBERARBG',
 'MBERARBO',
 'MSKA',
 'MSKB1',
 'MSKB2',
 'MSKC',
 'MSKD',
 'MHHUUR',
 'MHKOOP',
 'MAUT1',
 'MAUT2',
 'MAUT0',
 'MZFONDS',
 'MZPART',
 'MINKM30',
 'MINK3045',
 'MINK4575',
 'MINK7512',
 'MINK123M',
 'MINKGEM',
 'MKOOPKLA',
 'PWAPART',
 'PWABEDR',
 'PWALAND',
 'PPERSAUT',
 'PBESAUT',
 'PMOTSCO',
 'PVRAAUT',
 'PAANHANG',
 'PTRACTOR',
 'PWERKT',
 'PBROM',
 'PLEVEN',
 'PPERSONG',
 'PGEZONG',
 'PWAOREG',
 'PBRAND',
 'PZEILPL',
 'PPLEZIER',
 'PFIETS',
 'PINBOED',
 'PBYSTAND',
 'AWAPART',
 'AWABEDR',
 'AWALAND',
 'APERSAUT',
 'ABESAUT',
 'AMOTSCO',
 'AVRAAUT',
 'AAANHANG',
 'ATRACTOR',
 'AWERKT',
 'ABROM',
 'ALEVEN',
 'APERSONG',
 'AGEZONG',
 'AWAOREG',
 'ABRAND',
 'AZEILPL',
 'APLEZIER',
 'AFIETS',
 'AINBOED',
 'ABYSTAND',
 'CARAVAN',
 'ORIGIN_test',
 'ORIGIN_train']

In [120]:
df[numerical_col]=scaler.fit_transform(df[numerical_col])

In [121]:
df.head()

,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,MRELGE,...,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,CARAVAN,ORIGIN_test,ORIGIN_train
0,0.800,0.0,0.4,0.2,0.777778,0.000000,0.555556,0.2,0.333333,0.777778,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.900,0.0,0.2,0.2,0.777778,0.111111,0.444444,0.2,0.444444,0.666667,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.900,0.0,0.2,0.2,0.777778,0.000000,0.444444,0.4,0.444444,0.333333,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.200,0.0,0.4,0.4,0.222222,0.222222,0.333333,0.4,0.444444,0.555556,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.975,0.0,0.6,0.2,1.000000,0.111111,0.444444,0.2,0.444444,0.777778,...,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [122]:
x=df.drop('MGODPR',axis=1)

In [123]:
y=df['MGODPR']

In [124]:
from sklearn.model_selection import train_test_split

In [125]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [126]:
from sklearn.linear_model import LinearRegression

In [127]:
lr=LinearRegression()

In [128]:
lr

LinearRegression()

In [129]:
lr.fit(x_train,y_train)

LinearRegression()

In [130]:
y_pred=lr.predict(x_test)

In [131]:
y_pred

array([0.28694726, 0.38570788, 0.67650009, ..., 0.52270638, 0.41561949,
       0.21305643])

In [132]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_test,y_pred)

In [133]:
print(r2)
print(mse)
print(rmse)
print(mae)

0.9111396123213815
0.00304995824577282
0.0552264270596317
0.042612379559612605