In [3]:
import pandas as pd
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/heart_cleveland_upload (1) (1).csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        297 non-null    int64
 1   sex        297 non-null    int64
 2   cp         297 non-null    int64
 3   trestbps   297 non-null    int64
 4   chol       297 non-null    int64
 5   fbs        297 non-null    int64
 6   restecg    297 non-null    int64
 7   thalach    297 non-null    int64
 8   exang      297 non-null    int64
 9   oldpeak    297 non-null    float64
 10  slope      297 non-null    int64
 11  ca         297 non-null    int64
 12  thal       297 non-null    int64
 13  condition  297 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.6 KB

# SVC

In [5]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('condition')
df[num_col]=scaler.fit_transform(df[num_col])

In [7]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,0.833333,1.0,0.0,0.622642,0.246575,1.0,1.0,0.458015,0.0,0.016129,0.5,0.333333,0.0,0
1,0.833333,0.0,0.0,0.433962,0.257991,0.0,0.0,0.610687,0.0,0.290323,0.0,0.666667,0.0,0
2,0.770833,0.0,0.0,0.528302,0.228311,0.0,0.0,0.328244,0.0,0.419355,1.0,0.000000,0.0,0
3,0.750000,1.0,0.0,0.415094,0.356164,1.0,1.0,0.786260,0.0,0.225806,0.5,0.333333,0.0,1
4,0.729167,1.0,0.0,0.150943,0.194064,0.0,1.0,0.557252,1.0,0.290323,0.5,0.000000,0.0,0

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x=df.drop('condition',axis=1)

In [10]:
y=df['condition']

In [11]:
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [12]:
from sklearn.svm import SVC, SVR

In [13]:
svc=SVC(kernel='linear',C=1.0)

In [14]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [15]:
y_pred=svc.predict(x_test)

In [16]:
y_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0])

In [17]:
from sklearn.metrics import classification_report

In [18]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.77      0.72      0.74        32
           1       0.70      0.75      0.72        28

    accuracy                           0.73        60
   macro avg       0.73      0.73      0.73        60
weighted avg       0.74      0.73      0.73        60

In [19]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.77      0.72      0.74        32
           1       0.70      0.75      0.72        28

    accuracy                           0.73        60
   macro avg       0.73      0.73      0.73        60
weighted avg       0.74      0.73      0.73        60

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        297 non-null    float64
 1   sex        297 non-null    float64
 2   cp         297 non-null    float64
 3   trestbps   297 non-null    float64
 4   chol       297 non-null    float64
 5   fbs        297 non-null    float64
 6   restecg    297 non-null    float64
 7   thalach    297 non-null    float64
 8   exang      297 non-null    float64
 9   oldpeak    297 non-null    float64
 10  slope      297 non-null    float64
 11  ca         297 non-null    float64
 12  thal       297 non-null    float64
 13  condition  297 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 32.6 KB

# SVR

In [21]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,0.833333,1.0,0.0,0.622642,0.246575,1.0,1.0,0.458015,0.0,0.016129,0.5,0.333333,0.0,0
1,0.833333,0.0,0.0,0.433962,0.257991,0.0,0.0,0.610687,0.0,0.290323,0.0,0.666667,0.0,0
2,0.770833,0.0,0.0,0.528302,0.228311,0.0,0.0,0.328244,0.0,0.419355,1.0,0.000000,0.0,0
3,0.750000,1.0,0.0,0.415094,0.356164,1.0,1.0,0.786260,0.0,0.225806,0.5,0.333333,0.0,1
4,0.729167,1.0,0.0,0.150943,0.194064,0.0,1.0,0.557252,1.0,0.290323,0.5,0.000000,0.0,0

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('chol')
df[num_col]=scaler.fit_transform(df[num_col])

In [23]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,0.833333,1.0,0.0,0.622642,0.246575,1.0,1.0,0.458015,0.0,0.016129,0.5,0.333333,0.0,0.0
1,0.833333,0.0,0.0,0.433962,0.257991,0.0,0.0,0.610687,0.0,0.290323,0.0,0.666667,0.0,0.0
2,0.770833,0.0,0.0,0.528302,0.228311,0.0,0.0,0.328244,0.0,0.419355,1.0,0.000000,0.0,0.0
3,0.750000,1.0,0.0,0.415094,0.356164,1.0,1.0,0.786260,0.0,0.225806,0.5,0.333333,0.0,1.0
4,0.729167,1.0,0.0,0.150943,0.194064,0.0,1.0,0.557252,1.0,0.290323,0.5,0.000000,0.0,0.0

In [24]:
svr=SVR(kernel='rbf',C=0.5)

In [25]:
svr

SVR(C=0.5)

In [26]:
svr.fit(x_train,y_train)

SVR(C=0.5)

In [27]:
y_pred=svr.predict(x_test)

In [28]:
y_pred

array([ 0.91851162,  0.80358915,  0.4400846 , -0.07166811,  0.56301831,
        0.04499025,  0.99436545,  0.92618683,  0.63967722,  0.11702927,
        0.08945077,  0.65394219,  0.58052086, -0.13907965, -0.08869302,
        0.63288   ,  0.78422304, -0.01417122,  1.02107008, -0.02080534,
        0.98577969,  0.60145486,  0.01578734,  0.06185733,  0.14332851,
        1.08287204,  1.02865384,  0.87962634,  0.31610524,  0.72700801,
        0.69328764,  0.84197075,  0.11259756,  0.09131455,  0.49825799,
        1.07179669,  0.7969809 , -0.04218762,  1.07843198,  0.15070604,
       -0.0814629 ,  0.84145302,  0.68204218,  0.37275958, -0.05184179,
        0.99371234,  0.06351492,  0.40045367,  0.41780942, -0.07243382,
        0.17541732,  0.91298073,  0.33356472,  0.58077694,  1.05252748,
        0.50138413,  0.23270787,  1.06611908,  0.22785623,  0.46777414])

In [29]:
from sklearn.metrics  import r2_score, mean_absolute_error

In [30]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [31]:
print(r2)
print(mae)

0.30436334894613326
0.2975227762807099

In [32]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [33]:
print(r2)
print(mae)

0.30436334894613326
0.2975227762807099

In [34]:
print(r2)
print(mae)

0.30436334894613326
0.2975227762807099

In [35]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [36]:
rfc=RandomForestClassifier()
rfr=RandomForestRegressor()

In [37]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [38]:
y_pred=rfc.predict(x_test)

In [39]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.80      0.75      0.77        32
           1       0.73      0.79      0.76        28

    accuracy                           0.77        60
   macro avg       0.77      0.77      0.77        60
weighted avg       0.77      0.77      0.77        60

In [40]:
rfr.fit(x_train,y_train)

RandomForestRegressor()

In [41]:
y_pred=rfr.predict(x_test)

In [42]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [43]:
print(r2)
print(mae)

0.3263995535714288
0.3088333333333334