In [45]:
import pandas as pd

In [46]:
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/heart_cleveland_upload (1) (1).csv')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        297 non-null    int64
 1   sex        297 non-null    int64
 2   cp         297 non-null    int64
 3   trestbps   297 non-null    int64
 4   chol       297 non-null    int64
 5   fbs        297 non-null    int64
 6   restecg    297 non-null    int64
 7   thalach    297 non-null    int64
 8   exang      297 non-null    int64
 9   oldpeak    297 non-null    float64
 10  slope      297 non-null    int64
 11  ca         297 non-null    int64
 12  thal       297 non-null    int64
 13  condition  297 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.6 KB

In [48]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

# Random Forest

In [49]:
x=df.drop('condition',axis=1)

In [50]:
x.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0
5,64,1,0,170,227,0,2,155,0,0.6,1,0,2
6,63,1,0,145,233,1,2,150,0,2.3,2,0,1
7,61,1,0,134,234,0,0,145,0,2.6,1,2,0
8,60,0,0,150,240,0,0,171,0,0.9,0,0,0
9,59,1,0,178,270,0,2,145,0,4.2,2,0,2

In [51]:
y=df['condition']

In [52]:
y.value_counts()

condition
0    160
1    137
Name: count, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [55]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
rf=RandomForestClassifier()

In [57]:
rf

RandomForestClassifier()

In [58]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [59]:
y_pred=rf.predict(x_test)

In [60]:
y_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1])

In [61]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
167,66,0,3,178,228,1,0,165,1,1.0,1,2,2
211,59,1,3,140,177,0,0,162,1,0.0,0,1,2
63,41,1,1,135,203,0,0,132,0,0.0,1,0,1
154,37,0,2,120,215,0,0,170,0,0.0,0,0,0
5,64,1,0,170,227,0,2,155,0,0.6,1,0,2
77,68,0,2,120,211,0,2,115,0,1.5,1,0,0
183,63,1,3,130,330,1,2,132,1,1.8,0,3,2
158,70,1,3,130,322,0,2,109,0,2.4,1,3,0
9,59,1,0,178,270,0,2,145,0,4.2,2,0,2
139,44,1,2,130,233,0,0,179,1,0.4,0,0,0
285,43,1,3,150,247,0,0,171,0,1.5,0,0,0
78,68,1,2,118,277,0,0,151,0,1.0,0,1,2
92,61,1,2,150,243,1,0,137,1,1.0,1,0,0
101,58,0,2,120,340,0,0,172,0,0.0,0,0,0
42,55,0,1,132,342,0,0,166,0,1.2,0,0,0
222,58,1,3,100,234,0,0,156,0,0.1,0,1,2
283,43,0,3,132,341,1,2,136,1,3.0,1,0,2
33,57,0,1,130,236,0,2,174,0,0.0,1,1,0
263,50,1,3,150,243,0,2,128,0,2.6,1,0,2
148,41,1,2,112,250,0,0,179,0,0.0,0,0,0
245,54,1,3,120,188,0,0,113,0,1.4,1,1,2
45,54,1,1,192,283,0,2,195,0,0.0,0,1,2
60,44,1,1,130,219,0,2,188,0,0.0,0,0,0
46,52,1,1,120,325,0,0,172,0,0.2,0,0,0
278,45,1,3,115,260,0,2,185,0,0.0,0,0,0
237,56,1,3,132,184,0,2,105,1,2.1,1,1,1
175,64,1,3,145,212,0,2,132,0,2.0,1,2,1
234,56,0,3,200,288,1,2,133,1,4.0,2,2,2
17,51,1,0,125,213,0,2,125,1,1.4,0,1,0
279,44,1,3,120,169,0,0,144,1,2.8,2,0,1
111,54,1,2,150,232,0,2,165,0,1.6,0,0,2
219,58,0,3,170,225,1,2,146,1,2.8,1,2,1
24,71,0,1,160,302,0,0,162,0,0.4,0,2,0
82,66,0,2,146,278,0,2,152,0,0.0,1,1,0
7,61,1,0,134,234,0,0,145,0,2.6,1,2,0
75,69,1,2,140,254,0,2,146,0,2.0,1,3,2
108,54,1,2,120,258,0,2,147,0,0.4,1,0,2
84,65,0,2,155,269,0,0,148,0,0.8,0,0,0
90,62,1,2,130,231,0,0,146,0,1.8,1,3,2
73,71,0,2,110,265,1,2,130,0,0.0,0,1,0
116,52,0,2,136,196,0,2,169,0,0.1,1,0,0
126,50,1,2,140,233,0,0,163,0,0.6,1,1,2
233,57,1,3,132,207,0,0,168,1,0.0,0,0,2
59,44,1,1,120,263,0,0,173,0,0.0,0,0,2
195,61,0,3,130,330,0,2,169,0,0.0,0,0,0
208,59,1,3,110,239,0,2,142,1,1.2,1,1,2
97,59,1,2,150,212,1,0,157,0,1.6,0,0,0
185,62,0,3,140,268,0,2,160,0,3.6,2,2,0
176,64,0,3,130,303,0,0,122,0,2.0,1,2,0
124,51,0,2,120,295,0,2,157,0,0.6,0,0,0
93,60,1,2,140,185,0,2,155,0,3.0,1,0,0
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2
182,63,0,3,124,197,0,0,136,1,0.0,1,0,0
275,45,1,3,104,208,0,2,148,1,3.0,1,0,0
192,61,1,3,120,260,0,0,140,1,3.6,1,1,2
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2
25,70,1,1,156,245,0,2,143,0,0.0,0,0,0
224,57,1,3,150,276,0,2,112,1,0.6,1,1,1
6,63,1,0,145,233,1,2,150,0,2.3,2,0,1
181,63,0,3,108,269,0,0,169,1,1.8,1,2,0

In [62]:
#Evaluation
from sklearn.metrics import classification_report, accuracy_score

In [63]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [64]:
print(report)
print(score)

              precision    recall  f1-score   support

           0       0.74      0.72      0.73        32
           1       0.69      0.71      0.70        28

    accuracy                           0.72        60
   macro avg       0.72      0.72      0.72        60
weighted avg       0.72      0.72      0.72        60

0.7166666666666667

In [65]:
#Decision Tree Classifier

In [66]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [67]:
dt=DecisionTreeClassifier()
lg=LogisticRegression()

In [68]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [69]:
y_pred=dt.predict(x_test)

In [70]:
y_pred

array([1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [71]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [72]:
print(report)
print(score)

              precision    recall  f1-score   support

           0       0.73      0.75      0.74        32
           1       0.70      0.68      0.69        28

    accuracy                           0.72        60
   macro avg       0.72      0.71      0.71        60
weighted avg       0.72      0.72      0.72        60

0.7166666666666667

In [73]:
#Logistic Regression
lg.fit(x_train,y_train)

/Users/a1/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [74]:
y_pred=lg.predict(x_test)

In [75]:
y_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0])

In [76]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [77]:
print(report)
print(score)

              precision    recall  f1-score   support

           0       0.77      0.72      0.74        32
           1       0.70      0.75      0.72        28

    accuracy                           0.73        60
   macro avg       0.73      0.73      0.73        60
weighted avg       0.74      0.73      0.73        60

0.7333333333333333

In [78]:
# Modelni saqlash
#Joblib

In [79]:
import joblib

In [80]:
from joblib import dump , load

In [81]:
dump(lg,'yurak_kasalliklari_predikti.joblib')

['yurak_kasalliklari_predikti.joblib']

In [82]:
lg

LogisticRegression()

In [83]:
dump(rf,'kasalliklari_predikti.joblib')

['kasalliklari_predikti.joblib']

In [84]:
model=load('kasalliklari_predikti.joblib')

In [85]:
model.predict(x_test)

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1])