In [1]:
import pandas as pd
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/appearances.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           object
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    object
 6   player_name             object
 7   competition_id          object
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), object(4)
memory usage: 169.3+ MB

In [3]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

In [4]:
df

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706801,4547798_811779,4547798,811779,985,985,2025-04-10,Alejandro Garnacho,EL,0,0,0,0,83
1706802,4547798_820374,4547798,820374,985,985,2025-04-10,Kobbie Mainoo,EL,1,0,0,0,7
1706803,4547798_923831,4547798,923831,985,985,2025-04-10,Leny Yoro,EL,0,0,1,0,90
1706804,4547798_926952,4547798,926952,985,985,2025-04-10,Patrick Dorgu,EL,0,0,0,0,90
1706805,4547798_93720,4547798,93720,1041,1041,2025-04-10,Alexandre Lacazette,EL,0,0,0,0,39

# Data bilan tanishuv

In [5]:
# Xar bir feautureni manosini tushunish
# Target qiymatlarni 
# Keraksiz bolgan ustunlarni tashlab yuborish

In [6]:
df.drop('player_name',axis=1,inplace=True)

In [7]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,ELQ,0,0,0,1,90

# Data Preprocessing

In [8]:
#Missing qiymatlar
df.isnull().sum()

appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

In [9]:
# Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [11]:
df=encodla(df)

In [12]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,55694,2231978,38004,853,235,0,6,0,0,2,0,90
1,55741,2233748,79232,8841,2698,1,13,0,0,0,0,90
2,55775,2234413,42792,6251,465,1,13,0,0,0,0,45
3,55776,2234418,73333,1274,6646,1,13,0,0,0,0,90
4,55777,2234421,122011,195,3008,1,13,0,0,0,1,90

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           int64
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    int64
 6   competition_id          int64
 7   yellow_cards            int64
 8   red_cards               int64
 9   goals                   int64
 10  assists                 int64
 11  minutes_played          int64
dtypes: int64(12)
memory usage: 156.3 MB

In [14]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,55694,2231978,38004,853,235,0,6,0,0,2,0,90
1,55741,2233748,79232,8841,2698,1,13,0,0,0,0,90
2,55775,2234413,42792,6251,465,1,13,0,0,0,0,45
3,55776,2234418,73333,1274,6646,1,13,0,0,0,0,90
4,55777,2234421,122011,195,3008,1,13,0,0,0,1,90

In [15]:
# Scaling
from sklearn.preprocessing import MinMaxScaler
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int32','int64']).columns.drop('goals')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [16]:
df=scaling_qil(df)

In [17]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.032631,0.008627,0.027515,0.007724,0.002140,0.000000,0.142857,0.0,0.0,2,0.000000,0.605442
1,0.032658,0.009377,0.057371,0.080144,0.024469,0.000268,0.309524,0.0,0.0,0,0.000000,0.605442
2,0.032678,0.009658,0.030982,0.056663,0.004225,0.000268,0.309524,0.0,0.0,0,0.000000,0.299320
3,0.032679,0.009660,0.053099,0.011541,0.060261,0.000268,0.309524,0.0,0.0,0,0.000000,0.605442
4,0.032679,0.009662,0.088351,0.001759,0.027279,0.000268,0.309524,0.0,0.0,0,0.166667,0.605442

# Training

In [18]:
x=df.drop('goals',axis=1)

In [19]:
y=df['goals']

In [20]:
from sklearn.model_selection import  train_test_split

In [21]:
x_train, x_test,y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [22]:
df['goals'].value_counts()

goals
0    1560446
1     130986
2      13631
3       1572
4        147
5         23
6          1
Name: count, dtype: int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           float64
 1   game_id                 float64
 2   player_id               float64
 3   player_club_id          float64
 4   player_current_club_id  float64
 5   date                    float64
 6   competition_id          float64
 7   yellow_cards            float64
 8   red_cards               float64
 9   goals                   int64
 10  assists                 float64
 11  minutes_played          float64
dtypes: float64(11), int64(1)
memory usage: 156.3 MB

In [24]:
df.head(3)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.032631,0.008627,0.027515,0.007724,0.002140,0.000000,0.142857,0.0,0.0,2,0.0,0.605442
1,0.032658,0.009377,0.057371,0.080144,0.024469,0.000268,0.309524,0.0,0.0,0,0.0,0.605442
2,0.032678,0.009658,0.030982,0.056663,0.004225,0.000268,0.309524,0.0,0.0,0,0.0,0.299320